# Generated by Django 3.2.5 on 2022-02-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sector',
            old_name='related_curse',
            new_name='related_course',
        ),
    ]
